CDS - Creation of Tables and Routes for Dogs
ctc-uci/cell-dogs-backend pull request #7
Opened 2022-11-20 07:23 UTC by ctc-devops

Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #5

2022-11-20 07:24 UTC, ctc-devops commented on routes/dog.js
> +    console.log(dog);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-11-20 07:32 UTC, ArjunSivakumar13 commented
ignore the commits with temp.txt and the schema folder, I forgot to make the schema folder on the first commit

2022-11-20 07:56 UTC, claudeisakeeb requested changes
Good work so far Emmy and Arjun, just some optimizations and this should be good to go!

2022-11-20 07:56 UTC, claudeisakeeb commented on routes/dog.js
> +dog.put('/:dog_id', async (req, res) => {
Let's try object destructuring here :)
Here's an [example ](https://github.com/ctc-uci/find-your-anchor-backend/blob/dev/routes/anchorBox.js#L95)

2022-11-20 07:56 UTC, claudeisakeeb commented on routes/dog.js
> +    if (facility_id !== '') {
The way this is implemented right now there can be like 30+ async calls for 1 backend request. Can we include some conditionals and make it mirror [this ](https://github.com/ctc-uci/find-your-anchor-backend/blob/dev/services/boxHistoryService.js#L139)so that there's only ever 1 async call to the postgres instance?

2022-11-20 07:56 UTC, claudeisakeeb commented on routes/dog.js
> +    if (facility_id !== '') {
You'll have to use the db object initialized in server.js not pool because you can only accomplish this with pg-promise

2022-11-20 07:56 UTC, claudeisakeeb commented on routes/dog.js
> +      await pool.query(`UPDATE dog SET facility_id = '${facility_id}' WHERE dog_id = '${dog_id}'`);
Inserting the IDs directly into the sql string leaves us wide open to SQL injections! Read more [here](https://portswigger.net/web-security/sql-injection)
When you convert this to the example above you can use named parameters instead (the link above shows you how on line 160, note the syntax of the inserted variables ie `$()` instead of `${}`)

2022-11-20 07:56 UTC, claudeisakeeb commented on server/schema/dog.sql
> +INSERT INTO dog(dog_id, facility_id, group_num, grad_date, dog_name, age, shelter, breed, chip_type, chip_num, gender, profile_pic,
There's no need to include these INCLUDE statements as they were just used for testing. You can just remove these

2022-11-20 07:56 UTC, claudeisakeeb commented on routes/dog.js
> +    response.send(allRows.rows);
nitpick: Let's reword this to response.status(200).send(...). It's good to be explicit so everything is clear. Please do this for the rest of the file too :)

2022-11-20 07:56 UTC, claudeisakeeb commented on server/schema/dog.sql
> +CREATE TYPE vax AS ENUM('Female-Spayed', 'Male-Neutered', 'Male', 'Female');
noice

2022-11-20 07:57 UTC, claudeisakeeb commented on routes/dog.js
> +dog.put('/:dog_id', async (req, res) => {
Also lets make the param variables in this file all camelCase

2023-01-27 06:57 UTC, ctc-devops commented on server/db.js
> +console.log(pool);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2023-01-27 06:59 UTC, merged