Create Postgres Table and Routes for Users
ctc-uci/cell-dogs-backend pull request #9
Opened 2022-11-21 21:25 UTC by ctc-devops

Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #4

2022-11-21 21:51 UTC, claudeisakeeb requested changes
Good job so far!

Had some minor comments but the bigger one is to convert from pool to db and use named parameters to prevent SQL injections. Also can we get rid of the yarn.lock file? Let me know if y'all have any questions :D

2022-11-21 21:51 UTC, claudeisakeeb commented on server/schema/user.sql
> +    id SERIAL NOT NULL,
This is good for now, but let's leave a TODO to change this eventually because the ID will eventually be the user's firebase user ID

2022-11-21 21:51 UTC, claudeisakeeb commented on routes/users.js
> +const express = require('express');
Inserting the IDs directly into the sql string leaves us wide open to SQL injections! Read more [here](https://portswigger.net/web-security/sql-injection)
Instead, let's use a library called pg-promise and use [named parameters](https://github.com/vitaly-t/pg-promise#named-parameters) to insert the values safely. If you look in server.js there should already be an instance initialized called db so you can use that in place of pool. Here's an [example ](https://github.com/ctc-uci/find-your-anchor-backend/blob/dev/services/boxHistoryService.js#L261)from last year. 
Lmk if you have any questions :D

2022-11-21 21:51 UTC, claudeisakeeb commented on routes/users.js
> +    try {
noice

2022-11-21 21:51 UTC, claudeisakeeb commented on routes/users.js
> +      `insert into public.user (id, email, first_name, last_name, facility) values ('${id}', '${email}', '${firstName}', '${lastName}', ${facility}) returning *`,
this is super nitpick but can we make the keywords all CAPS so it's easier to read?
this line can be something like INSERT INTO USER (...) VALUES(...) RETURNING *

Can y'all also do that for the rest of the file xd

2022-11-21 21:51 UTC, claudeisakeeb commented on server/schema/dummy.sql
> +insert into public.user (id, email, first_name, last_name, facility)
Let's remove this file as these SQL statements were only used for testing purposes :)
If we leave them in these sql files will get cluttered and it'll be more confusing to navigate

2022-11-21 21:51 UTC, claudeisakeeb commented on server/schema/user.sql
> +CREATE TABLE IF NOT EXISTS public."user"
I believe you can just do CREATE TABLE IF NOT EXISTS user (you don't need public or the quotes). It'll just make the code simpler.

2022-11-21 21:51 UTC, claudeisakeeb commented on routes/users.js
> +const user = express.Router(); // This should be an express.Router instance;
SUPER NITPICK: Can we just change this from express.Router() to express()? There's like basically no difference but it's just simpler xd

2023-01-12 00:06 UTC, Madhu2244 approved these changes

2023-01-12 00:07 UTC, merged